# SkyPunch Database schema
# pemellquist@gmail.com

DROP DATABASE IF EXISTS skypunch;
CREATE DATABASE skypunch;
USE skypunch;

# versions, used to define overall version for schema
# major version differences are not backward compatibile
create TABLE versions (
   major     INT                       NOT NULL,
   minor     INT                       NOT NULL,
   PRIMARY KEY (major) 
);
INSERT INTO versions values (1,0);

# targets 
CREATE TABLE targets ( 
    id                 BIGINT                   NOT NULL AUTO_INCREMENT,  # unique id for this target, generated by DB when record is created
    name               VARCHAR(128)             NOT NULL,                 # tenant assigned target name
    tenantid           VARCHAR(128)             NOT NULL,                 # tenant id who owns this target 
    status             VARCHAR(50)              NOT NULL,                 # current status (NEW, PASS, FAIL)
    status_description VARCHAR(128),                                      # description for status
    previous_status    VARCHAR(50)              NOT NULL,                 # previous status (used to determine edge status)
    last_updated       TIMESTAMP                NOT NULL,                 # time that this target was last updated
    url                VARCHAR(256)             NOT NULL,                 # URL of target to use
    method             VARCHAR(128)             NOT NULL,                 # method to use with URL (GET,POST,DELETE,PUT,HEAD,PATCH)
    authn              VARCHAR(128)             NOT NULL,                 # Authentication method (NONE,BASIC,OPENSTACK)
    authn_parms        VARCHAR(256),                                      # Auth params used e.g. user=xxxx,password=yyyy [osauthendpoint=zzzz,tenantid=tttttt]
    pass_result        INT                      NOT NULL,                 # result code for success ( e.g. 200 )
    frequency          INT                      NOT NULL,                 # frequency to punch this target in seconds
    timeout            INT                      NOT NULL,                 # timeout in seconds for this request
    pass_count         BIGINT                   NOT NULL,                 # times that this target was punched with success
    fail_count         BIGINT                   NOT NULL,                 # times that this target was punched with failure
    count200           BIGINT                   NOT NULL,                 # 200 series response count
    count300           BIGINT                   NOT NULL,                 # 300 series response count
    count400           BIGINT                   NOT NULL,                 # 400 series response count
    count500           BIGINT                   NOT NULL,                 # 500 series response count
    network_fails      BIGINT                   NOT NULL,                 # network connect or read errors or timeouts
    repeated_fails     BIGINT                   NOT NULL,                 # current number of repeated failures
    enabled            BOOLEAN                  NOT NULL,                 # is this target enabled to be checked? 
    PRIMARY KEY (id)                                                      # id of targets 
 ) DEFAULT CHARSET utf8 DEFAULT COLLATE utf8_general_ci;


# notifiers
CREATE TABLE notifiers (
    id                 BIGINT                   NOT NULL AUTO_INCREMENT,  # unique id for this notifier, generated by DB when record is created
    name               VARCHAR(128)             NOT NULL,                 # name of notifier
    type               VARCHAR(50)              NOT NULL,                 # type of notifier (SMTP)
    address            VARCHAR(128)             NOT NULL,                 # who to notify ( e.g. with SMTP this is the email address ) 
    params             VARCHAR(128)             NOT NULL,                 # params based on type user=xxxx,password=yyyy,server=zzzzz
    pass_count         BIGINT                   NOT NULL,                 # times this notifier has been sent with success
    fail_count         BIGINT                   NOT NULL,                 # times this notifier has been sent with failure 
    enabled            BOOLEAN                  NOT NULL,                 # is this notifier enabled to be sent to?
    PRIMARY KEY (id)                                                      # id of notifier 
) DEFAULT CHARSET utf8 DEFAULT COLLATE utf8_general_ci;
 
